### PR TITLE
7.x backport updates

### PR DESCRIPTION
**Pull request by tadayosi**
Cumulative backports from master to 7.x product branch, excepts the ones related to Artemis integration ( #58 ).

### CODE REVIEW

**Comment by tadayosi** [comment]
@astefanutti Sorry for the long list but they're just mechanical cherry-picks from master.

**Review by astefanutti — COMMENTED** [review]
I don't think the `1.x-redhat-7.x` is actually used anymore:

https://github.com/jboss-fuse/fuse-jenkins-pipelines/blob/5556a5deb53c09283ae174aee903f44a117d7d4d/7.7/projects-images.json#L14

My understanding is that we can branch `1.x-redhat-7.8.x` off `master` branch, unless there are changes that should be excluded?

**Comment by tadayosi** [comment]
@astefanutti `1.x-redhat-7.x` is used here at this moment (probably until the next code freeze?):
https://github.com/jboss-fuse/fuse-jenkins-pipelines/blob/5556a5deb53c09283ae174aee903f44a117d7d4d/7.8/projects-sb2.json#L545
I saw the `release-work-1.0.0.fuse-780` branch has stemmed from `1.x-redhat-7.x` already in this repo.

**Comment by astefanutti** [comment]
@tadayosi ah right! what commits do you think have to be excluded? My understanding is that the changes introduced to prepare the Artemis support are ok to be included, aren't they?

**Review by oscerd — APPROVED** [review]

**Comment by tadayosi** [comment]
@astefanutti Yes, for traceability I plan to separate this normal update merge commit from the one for the Artemis integration work. I'll send a separate pull req for the commits related to Artemis support.

**Comment by astefanutti** [comment]
@tadayosi sounds good to me. Maybe we can branch `1.x-redhat-7.8.x` off `1.x-redhat-7.x` when it's updated.

**Review by astefanutti — APPROVED** [review]

**Comment by tadayosi** [comment]
Ah ok, this repo doesn't allow merge commits. Let's rebase and merge it.

**Comment by astefanutti** [comment]
> Ah ok, this repo doesn't allow merge commits. Let's rebase and merge it.

We can enable them if that ease things.

**Comment by tadayosi** [comment]
@astefanutti Yes, at least for the product branches I see merge commits are more traceable than flat commit lines. I promise I don't abuse them on upstream ;-)  Let me enable it on the repo then. Thanks.

**Pull request merged**
