### PR TITLE
Implementation of Form Authentication

### PR DESCRIPTION
**Pull request by phantomjinx**
Merging of this is dependent on a version of [hawtio-next](https://github.com/hawtio/hawtio-next) that includes the PR [#607](https://github.com/hawtio/hawtio-next/pull/607) being released.

### CODE REVIEW

**Comment by phantomjinx** [comment]
Note: Tests will remain in a failed state until the release of a new version of hawtio-next that supports required changes in API.

**Comment by phantomjinx** [comment]
https://github.com/hawtio/hawtio-next/pull/607 now merged.

Needs to be updated with new release version of `hawtio/react` once latter is made.

**Comment by tadayosi** [comment]
@phantomjinx hawtio/react v0.6.0 is already released so you can use it. However, I found an issue that it restarts the jolokia instance everytime the jolokia service getJolokia() is invoked. We need to release v0.6.1 soon that fixes it.

**Comment by phantomjinx** [comment]
> @phantomjinx hawtio/react v0.6.0 is already released so you can use it. However, I found an issue that it restarts the jolokia instance everytime the jolokia service getJolokia() is invoked. We need to release v0.6.1 soon that fixes it.

Did you mean `getJolokiaUrl()`? Do you want me to fix this?

Updating hawtio-online presently. Thx!

**Comment by tadayosi** [comment]
@phantomjinx Already fixed it with v0.6.1.

**Comment by phantomjinx** [comment]
Now upgraded dependency to @hawtio/react 0.6.1

**Pull request merged**
